[theme]
theme = "slick"
[icons]
icons = "awesome4"

[[block]]
block = "pomodoro"

[[block]]
block = "disk_iostats"

[[block]]
block = "disk_space"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"

[[block]]
block = "net"

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%d-%m-%y %R')"

[[block]]
block = "sound"
step_width = 5
max_vol = 150

